[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_program = "HuyaDbbnjpkJK78DmzkvTSiNQVgmsS1XcXU2wp6iWqF"

[programs.devnet]
stake_program = "HuyaDbbnjpkJK78DmzkvTSiNQVgmsS1XcXU2wp6iWqF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
